# Generated by Django 3.0 on 2020-03-11 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_vaccancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('no_of_opening', models.CharField(max_length=100, null=True)),
                ('apply_date', models.DateField(default='2020/02/21')),
                ('last_date', models.DateField(default='2020/05/19')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='', upload_to='pcapp/Files/')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('address', models.TextField(max_length=300, null=True)),
                ('pwd', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('CE', 'CE')], max_length=100, null=True)),
                ('selected', models.CharField(choices=[('Selected', 'Selected'), ('Not Selected', 'Not Selected')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=100)),
                ('s_e_num', models.CharField(default='', max_length=100)),
                ('s_sem', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=100, null=True)),
                ('s_branch', models.CharField(choices=[('IT', 'IT'), ('CE', 'CE')], max_length=100, null=True)),
                ('s_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('s_mobile', models.CharField(default='', max_length=100)),
                ('s_email', models.EmailField(default='', max_length=200)),
                ('s_ssc_per', models.CharField(default='', max_length=30)),
                ('s_hsc_per', models.CharField(default='', max_length=30)),
                ('s_cpi', models.CharField(default='10', max_length=10)),
                ('s_cgpa', models.CharField(default='10', max_length=10)),
                ('s_resume', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('s_profile', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('s_dob', models.DateTimeField(default='')),
                ('s_address', models.TextField(default='', max_length=300)),
                ('s_state', models.CharField(default='', max_length=15)),
                ('s_dist', models.CharField(default='', max_length=15)),
                ('s_pincode', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('pwd', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_update', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpo_update', models.TextField(default='1', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='screenshot_5.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='screenshot_7.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applied_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(default='00', max_length=100)),
                ('job_resume', models.FileField(help_text='(pdf,docx,doc)', upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcapp.Company')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcapp.Student')),
            ],
        ),
    ]
