# Generated by Django 3.0 on 2020-03-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
