# Generated by Django 3.0 on 2020-03-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0002_auto_20200311_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
