# Generated by Django 3.0 on 2020-04-06 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0005_auto_20200405_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_story',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='success_story',
            name='video',
            field=models.FileField(help_text='(mp4, m4p, m4v, MPEG)', upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'm4p', 'm4v', 'MPEG'])]),
        ),
    ]
