# Generated by Django 3.0 on 2020-04-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0006_auto_20200406_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_story',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pcapp.Student'),
        ),
    ]
